name = "kit_runtime"
description = "Runtime library for Kit"
version = "0.1.0-dev"
licenses= "GPL-3.0-or-later"

authors = ["Fraser Wilson"]
maintainers = ["Fraser Wilson <fraser@thewhitelion.eu>"]
maintainers-logins = ["blancolioni"]

tags = ["utility", "database", "compiler"]
website = "https://github.com/blancolioni/kit_builder"

[[depends-on]]
marlowe = "~0.1.0-dev"
[[depends-on]]
kit_base = "~0.1.0-dev"
